spring.application.name=OnlineLearningPlatformEurekaServer
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#spring.cloud.config.import-check.enabled=false
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.leaseRenewalIntervalInSeconds=30
eureka.instance.leaseExpirationDurationInSeconds=90 
