spring.application.name=OnlineLearningPlatformEurekaServer
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.config.enabled=true
spring.cloud.config.import-check.enabled=true
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
