spring.application.name=OnlineLearningPlatformConfigServer
server.port=8888

# Custom message to identify if the server is working
message=Config Server is up and running!

# Git repository configuration
spring.cloud.config.server.git.uri=https://github.com/AvanthiBulusu/Avanthi508.git
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_PASSWORD}
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.searchPaths=repo,repo/OnlineLearningPlatform,repo/OnlineLearningPlatformCourses,repo/OnlineLearningPlatformApiGateway,repo/OnlineLearningPlatformEurekaServer, repo/OnlineLearningPlatformApiGatewayCb

# Activate the desired profile
spring.profiles.active=git

# Actuator endpoints configuration
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
