spring.application.name=OnlineLearningPlatformApiGatewayCb
server.port=8085

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.metadata-map.instanceId=OnlineLearningPlatformApiGatewayHystrix-8085
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable Spring Cloud Gateway Auto-Discovery for Eureka Services
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Management and Logging Configurations
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE

spring.cloud.gateway.default-filters[0]=CircuitBreaker=defaultCB
spring.cloud.gateway.default-filters[1]=Retry
