spring.application.name=OnlineLearningPlatform
server.servlet.context-path=/OnlineLearningPlatform

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/OLP
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springfox.documentation.swagger.v2.path=/api-docs

jwt.secret=foo
jwt.expiration=3600000
