spring.application.name=OnlineLearningPlatformApiGateway

# Server port for API Gateway
server.port=8085

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Enable Spring Cloud Gateway auto-discovery for Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route for ONLINELEARNINGPLATFORM service
spring.cloud.gateway.routes[0].id=online-learning-platform
spring.cloud.gateway.routes[0].uri=lb://ONLINELEARNINGPLATFORM
spring.cloud.gateway.routes[0].predicates[0]=Path=/platform/**

# Rewrite path to include the context path of the service
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/platform/(?<segment>.*), /OnlineLearningPlatform/api/${segment}

# Add a header to log the request path for debugging
spring.cloud.gateway.globalfilters[0]=AddRequestHeader=X-Request-Path, ${request.path}

# Route for ONLINELEARNINGPLATFORMCOURSES service
spring.cloud.gateway.routes[1].id=online-learning-platform-courses
spring.cloud.gateway.routes[1].uri=lb://ONLINELEARNINGPLATFORMCOURSES
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=env
management.endpoint.env.show-values=always
management.endpoint.env.keys-to-sanitize=


